# This is a basic workflow that is manually triggered

name: 'Doxygen Build'

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    branches:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-page-content:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    # Checkout content repo
    - name: checkout
      uses: actions/checkout@master
      with:
        submodules: true
        ref: 'main'
    # make sure git is setup
    - name: branch_content
      run: |
        git checkout -b content
    - name: setup_git
      run: |
        git config --global user.name "Actions bot"
        git config --global user.email "<>"
        git config --global pull.rebase false
    # merge changes from main
    #- name: merge_main
    #  run: |
    #    git fetch --unshallow
    #    git merge --no-ff origin/main -m 'Automerge - main'
    # update fuka submodule
    - name: update_fuka
      continue-on-error: true # avoid failure if nothing to commit
      run: |
        cd fuka
        git pull origin fuka
        cd ..
        git commit fuka -m 'update to latest FUKA submodule'
        cd -
    - name: clear_docs dir
      run: |
        mkdir -p docs
        rm -rf docs*
    # rebuild fukaref doxygen content
    - name: build fukaref doxy
      continue-on-error: true #
      uses: mattnotmitt/doxygen-action@1.9.5
      with:
        working-directory: './'
        doxyfile-path: 'fuka.dox'
    - name: build fukahome doxy
      uses: mattnotmitt/doxygen-action@1.9.5
      with:
        working-directory: './'
        doxyfile-path: 'fuka_website.dox'
    # rebuild personal website doxygen
    - name: build website doxy
      uses: mattnotmitt/doxygen-action@1.9.5
      with:
        working-directory: './'
        doxyfile-path: 'Doxyfile'
    # Commit new content to 'content' branch
    - name: update branch
      run: |
        git add .
        git commit -a -m 'doxygen page update'
        git push -u -f origin content
