# This is a basic workflow that is manually triggered

name: 'Doxygen Build'

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  status:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: './'
    steps:
      - uses: actions/checkout@master
      - run: pwd
      - run: ls -al
  # This workflow contains a single job called "greet"
  build-doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 'doxygen/'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: Doxygen Action      
      uses: mattnotmitt/doxygen-action@1.9.5
      with:
        working-directory: 'doxygen/'
